GRANT SELECT ON TABLE pub_admin.PBA_VERSION TO PUBLIC;

GRANT SELECT ON TABLE pub_admin.PBA_PARAM_T TO PUBLIC;

GRANT SELECT ON TABLE pub_admin.PBA_EVENT_T TO PUBLIC;

GRANT SELECT,INSERT,DELETE ON pub_admin.pba_cnstrnt_t TO PUBLIC;