CREATE TABLE sbs_util.sbs_pg_session_lock
(
	id			INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	lock_name	VARCHAR(200),
	lock_key	BIGINT,
	CONSTRAINT sbs_pg_session_lock_pkey PRIMARY KEY (lock_name)
)