CREATE TABLE pub_admin.pba_event_name_hst_t
(
	event_name_hst_id	     INTEGER GENERATED BY DEFAULT AS IDENTITY,
	event_name_id		     INTEGER,
	event_constant		     VARCHAR(100) NOT NULL,
	event_name			     VARCHAR(256) NOT NULL,
	event_name_desc		     VARCHAR(1000),
	rcrd_create_user_id	     VARCHAR(30) NOT NULL,
	rcrd_create_ip		     VARCHAR(30) NOT NULL,
	rcrd_create_ts		     TIMESTAMPTZ NOT NULL,
	rcrd_dml_type_cd	     VARCHAR(5),
	rcrd_updt_user_id	     VARCHAR(30),
	rcrd_updt_ip		     VARCHAR(30),
	rcrd_updt_ts		     TIMESTAMPTZ,
	hst_rcrd_create_user_id  VARCHAR(30) NOT NULL, 
    hst_rcrd_create_ip 		 VARCHAR(30) NOT NULL,
    hst_rcrd_create_ts   	 TIMESTAMPTZ NOT NULL,
	CONSTRAINT pba_event_name_hst_pkey PRIMARY KEY (event_name_hst_id)
);