CREATE TABLE pub_admin.pba_version
(
    version_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description character varying(100),
    version character varying(50),
    comments character varying(500),
    applied_date timestamptz,
    status character varying(20),
    verification_date timestamptz,
    verified_by_username character varying(30),
    apply_method character varying(20),
    applied_by character varying(30),
    is_current integer,
    CONSTRAINT pk_pba_version PRIMARY KEY (version_id),
    CONSTRAINT pba_version_current_uk UNIQUE (is_current),
	CONSTRAINT pba_version_version_uk UNIQUE (version),
    CONSTRAINT pba_version_dates_ck CHECK (applied_date IS NOT NULL OR verification_date IS NOT NULL),
    CONSTRAINT pba_version_is_current_check CHECK (is_current = ANY (ARRAY[1, NULL::integer]))
);
GRANT DELETE, UPDATE, INSERT, TRUNCATE, SELECT ON TABLE pub_admin.pba_version TO PUBLIC;

COMMENT ON TABLE pub_admin.pba_version
    IS 'The version of this schema';

COMMENT ON COLUMN pub_admin.pba_version.applied_date
    IS 'Date/time the install or upgrade script for this release was successfully run.';

COMMENT ON COLUMN pub_admin.pba_version.status
    IS 'Designates the status of this PUB_ADMIN Package release. Values include VALIDATED and APPLIED.';

COMMENT ON COLUMN pub_admin.pba_version.verification_date
    IS 'Date/time the verification script for this release was last successfully run.';

COMMENT ON COLUMN pub_admin.pba_version.verified_by_username
    IS 'User who ran the most recent verification for this release.';

COMMENT ON COLUMN pub_admin.pba_version.apply_method
    IS 'Designates how the version was applied: INITIAL or UPGRADE.';

COMMENT ON COLUMN pub_admin.pba_version.applied_by
    IS 'User who ran the ''apply'' for this release.';

COMMENT ON COLUMN pub_admin.pba_version.is_current
    IS 'Indicates that this is the current version.';