CREATE TABLE pub_admin.pba_param_hst_t
(
	param_hst_id		INTEGER GENERATED BY DEFAULT AS IDENTITY,
	param_nm			     VARCHAR(30)	NOT NULL,
	param_value_txt		     VARCHAR(4000)	NOT NULL,
	param_dsc			     VARCHAR(4000)	NOT NULL,
	rcrd_create_user_id	     VARCHAR(30)	NOT NULL,
	rcrd_create_ip           VARCHAR(30),
	rcrd_create_ts		     TIMESTAMPTZ,
	rcrd_dml_type_cd	     VARCHAR(5),
    rcrd_updt_user_id        VARCHAR(30),
    rcrd_updt_ip             VARCHAR(30),
    rcrd_updt_ts             TIMESTAMPTZ,
    hst_rcrd_create_user_id  VARCHAR(30) NOT NULL, 
    hst_rcrd_create_ip 		 VARCHAR(30) NOT NULL,
    hst_rcrd_create_ts   	 TIMESTAMPTZ NOT NULL,
	CONSTRAINT pba_param_hst_pkey PRIMARY KEY (param_hst_id)
);